# Generated by Django 4.0.1 on 2022-01-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_criador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criador',
            old_name='autor',
            new_name='author',
        ),
    ]
