# Generated by Django 4.0.1 on 2022-01-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_autor_criador_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='texto',
            new_name='text',
        ),
        migrations.DeleteModel(
            name='Criador',
        ),
    ]
